#!/usr/bin/env bash

if [ "$1" == "container" ] && [ "$2" == "upgrade" ]; then
    # Call the upgrade script with the remaining parameters
    docker-upgrade.sh "${@:3}"
else
    # Pass all other commands to the original docker CLI
    /usr/bin/docker "$@"
fi